// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXJQ5vpw2CjQGetqqsbaEr7qk-OBxZPeQ',
    appId: '1:489751738826:web:348ab3de32b0077798f733',
    messagingSenderId: '489751738826',
    projectId: 'joke-app-73383',
    authDomain: 'joke-app-73383.firebaseapp.com',
    storageBucket: 'joke-app-73383.firebasestorage.app',
    measurementId: 'G-YE0JLBSR1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkS-FpCccZBgtRGPnISE17FyWK8Bucf4E',
    appId: '1:489751738826:android:6d2c65622e1bf4fd98f733',
    messagingSenderId: '489751738826',
    projectId: 'joke-app-73383',
    storageBucket: 'joke-app-73383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwB0vDngiz1NElzpq0OxLVpyBc8t-ZKS8',
    appId: '1:489751738826:ios:f4de6ebec1c6e83698f733',
    messagingSenderId: '489751738826',
    projectId: 'joke-app-73383',
    storageBucket: 'joke-app-73383.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwB0vDngiz1NElzpq0OxLVpyBc8t-ZKS8',
    appId: '1:489751738826:ios:f4de6ebec1c6e83698f733',
    messagingSenderId: '489751738826',
    projectId: 'joke-app-73383',
    storageBucket: 'joke-app-73383.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXJQ5vpw2CjQGetqqsbaEr7qk-OBxZPeQ',
    appId: '1:489751738826:web:feee9a882bf6188598f733',
    messagingSenderId: '489751738826',
    projectId: 'joke-app-73383',
    authDomain: 'joke-app-73383.firebaseapp.com',
    storageBucket: 'joke-app-73383.firebasestorage.app',
    measurementId: 'G-FVRMMC85ES',
  );
}
